### ISSUE TITLE
Help Installing jupyterlab_bokeh

### ISSUE THREAD

**Issue by itarec1988** [bokeh/jupyterlab_bokeh#11]
Hi!
I am new in this field.. I am doing some tutorials about bokeh and I am trying to display a plot inside the JupyterLab notebook. I know I need to install the jupyterlab_bokeh app but I can not manage to do from the terminal. I have the latest versions of:
bokeh                     0.12.10
jupyter                   1.0.0            
jupyter_client            5.1.0         
jupyter_console           5.2.0            
jupyter_core              4.3.0            
jupyterlab                0.27.0            
jupyterlab_launcher       0.4.0          
Thank you!

**Comment by IamGianluca** [comment]
I think I'm facing a similar issue:

```
$ jupyter labextension install jupyterlab_bokeh
> /usr/bin/npm pack jupyterlab_bokeh
jupyterlab_bokeh-0.1.0.tgz

Errored, use --debug for full output:
ValueError: 
"jupyterlab_bokeh@0.1.0" is not compatible with the current JupyterLab
Conflicting Dependencies:
JupyterLab                        Extension          Package
>=1.0.2-0 <2.0.0-0                >=0.4.0-0 <0.5.0-0 @jupyterlab/rendermime-interfaces
```
This is the `pip freeze` output:
```
$ pip freeze
bleach==2.1.2
bokeh==0.12.13
decorator==4.1.2
entrypoints==0.2.3
html5lib==1.0.1
ipykernel==4.7.0
ipython==6.2.1
ipython-genutils==0.2.0
jedi==0.11.1
Jinja2==2.10
jsonschema==2.6.0
jupyter-client==5.2.1
jupyter-core==4.4.0
jupyterlab==0.31.0
jupyterlab-launcher==0.10.2
MarkupSafe==1.0
mistune==0.8.3
nbconvert==5.3.1
nbformat==4.4.0
notebook==5.2.2
numpy==1.14.0
pandocfilters==1.4.2
parso==0.1.1
pexpect==4.3.1
pickleshare==0.7.4
prompt-toolkit==1.0.15
ptyprocess==0.5.2
Pygments==2.2.0
python-dateutil==2.6.1
PyYAML==3.12
pyzmq==16.0.3
simplegeneric==0.8.1
six==1.11.0
terminado==0.8.1
testpath==0.3.1
tornado==4.5.3
traitlets==4.3.2
wcwidth==0.1.7
webencodings==0.5.1
```

**Comment by blink1073** [comment]
Hi @IamGianluca, this will be fixed by #12 and a new release.

**Comment by IamGianluca** [comment]
Thanks, @blink1073 !

**Comment by canavandl** [comment]
I'm going to close this as resolved. Thanks for the report @itarec1988 - please reopen this or a new issue if you still have problems.
