### ISSUE TITLE
Task: Enable responsive sizing_modes

### ISSUE THREAD

**Issue by canavandl** [bokeh/jupyterlab_bokeh#14]
Currently setting ``layout.responsive=True`` will result in the plot being responsively sized on initial load. However resizing the JLab Panel (either by dragging the edge or moving the panel) doesn't cause the plot to resize. Presumably the window size change events aren't being triggered by the panels natively.

**Comment by bryevdv** [comment]
tested with 1.2 and `scale_wdth`, seems to work fine now
