### ISSUE TITLE
ValueError: setting 'version' makes sense only when 'mode' is set to 'cdn'

### ISSUE THREAD

**Issue by rjrussell77** [bokeh/jupyterlab_bokeh#30]
Total nube to bokeh on Jupyter Lab so pardon the ignorance but...
I'm seeing this error:
`
ValueError: setting 'version' makes sense only when 'mode' is set to 'cdn'
`
on the following line:
`
from bokeh.io import push_notebook, show, output_notebook
`
My Environment:
```
bokeh==0.12.14
jupyter==1.0.0
jupyter-client==5.2.3
jupyter-console==5.2.0
jupyter-core==4.4.0
jupyter-pip==0.3.1
jupyterhub==0.8.0
jupyterlab==0.31.8
jupyterlab-launcher==0.10.5
Python 3.6.2
run/s6/services/python$ jupyter labextension list
JupyterLab v0.31.8
Known labextensions:
   app dir: /opt/conda/share/jupyter/lab
@jupyterlab/plotly-extension
        @jupyterlab/plotly-extension v0.14.4  enabled  OK
jupyterlab_bokeh
        jupyterlab_bokeh v0.4.0  enabled  OK
```
Thanks for any help.

**Comment by rjrussell77** [comment]
Here is a screenshot for added effect
![screen shot 2018-03-20 at 10 36 40 am](https://user-images.githubusercontent.com/8116184/37672187-aa25b1c0-2c2a-11e8-931b-ca9ebb039a58.png)

**Comment by rjrussell77** [comment]
Things I've tried:
bokeh version 0.12.7
bokeh jupyterlab extension version 0.3.x

**Comment by rjrussell77** [comment]
@canavandl Any ideas here?

**Comment by philippjfr** [comment]
I would try upgrading to a more recent version of bokeh, 0.12.7 is quite out of date at this point.

**Comment by rjrussell77** [comment]
Thanks @philippjfr but if you notice in the top screen, it is failing with 0.12.14

**Comment by philippjfr** [comment]
Ah sorry, must have missed that somehow. The error is pretty strange, is it possible you've got some bokeh environment variables set?

**Comment by rjrussell77** [comment]
No, I don't think so.  This is a freshly spun-up instance of JupyterLab and a brand new notebook failing on the very first line.  I don't think we have an environmental config file setup for bokeh if such a thing exists.

**Comment by philippjfr** [comment]
Odd, tracing through the code the only scenario I can imagine causing this is if ``BOKEH_VERSION`` is defined. Seems unlikely given your setup but does this return anything?

```
import os
os.environ['BOKEH_VERSION']
```

**Comment by rjrussell77** [comment]
Looks good: 
![screen shot 2018-03-23 at 11 22 43 am](https://user-images.githubusercontent.com/8116184/37846981-970df598-2e8c-11e8-9415-b3cc5ae7afc6.png)

**Comment by rjrussell77** [comment]
Ok so we are setting that variable in our build config (Dockerfile).  Executing this in the notebook cell fixes the error: `%env BOKEH_VERSION=`

**Comment by philippjfr** [comment]
>Ok so we are setting that variable in our build config (Dockerfile).

Any idea why it's setting the variable? Wondering whether this is something that should be raised upstream, it's definitely not down to the jupyterlab extension.

**Comment by rjrussell77** [comment]
Yeah - so our dockerfile sets as env vars all of our third party dependencies:
```
# Specify versions of libs
ENV CONDA_VERSION=4.3 \
    PYTHON_VERSION=3.6.2 \
    NOTEBOOK_VERSION=5.4.0 \
    JUPYTERHUB_VERSION=0.8.0 \
    REQUESTS_VERSION=2.18.4 \
    PLOTLY_VERSION=2.0.12 \
    FOLIUM_VERSION=0.3.0 \
    IPYWIDGETS_VERSION=6.0.0 \
    SPARKMAGIC_VERSION=0.12.5 \
    BOKEH_VERSION=0.12.14 \
    GENSIM_VERSION=2.3.0 \
...
```
These are then used in a subsequent section **and** other sections:
```
# Install Jupyter Notebook and Libs
RUN ${CONDA_DIR}/bin/conda install --quiet --yes \
    "notebook==${NOTEBOOK_VERSION}" \
    "jupyterhub==${JUPYTERHUB_VERSION}" \
    "requests==${REQUESTS_VERSION}" \
    "plotly==${PLOTLY_VERSION}" \
    "folium==${FOLIUM_VERSION}" \
    "ipywidgets==${IPYWIDGETS_VERSION}" \
    "bokeh==${BOKEH_VERSION}" \
...
```
This strategy allows us to segment our Dockerfile per recommended guidance.

**Comment by rjrussell77** [comment]
I would think that it's a liability to have blocking code for a version declaration.  Perhaps an incorrect assumption is being made?

**Comment by philippjfr** [comment]
That's unfortunate, really just a matter of two different conventions clashing. I don't have any good suggestions, I'm inclined to say there's little that bokeh can do about this since ``BOKEH_VERSION`` has been around a long time but @bryevdv might have a suggestion.

**Comment by rjrussell77** [comment]
Ok thanks guys, for the thoughts and input.  I'd consider going deeper and/or providing some kind of mitigation when time allows but for now, at least we have a documented acknowledgement and work-around.

**Comment by bryevdv** [comment]
Not having gotten any other reports/complaints I am just going to go ahead and close this and leave it as documentation.

**Comment by bryevdv** [comment]
This will be changing to BOKEH_CDN_VERSION in Bokeh 2.0 see https://github.com/bokeh/bokeh/pull/9713
