### ISSUE TITLE
Resize handle feature

### ISSUE THREAD

**Issue by leolchat** [bokeh/jupyterlab_bokeh#32]
I am really missing the ability to resize the plot with the mouse like in the [picture](http://i.imgur.com/nqJo2Jn.png) with the grey bottom right corner.

**Comment by canavandl** [comment]
@leolchat I believe that was a Bokeh core (https://github.com/bokeh/bokeh) feature that was deprecated, and it's related to the jupyterlab_bokeh repo. I'm going to close this as referred - please open an issue w/ bokeh/bokeh

**Comment by leolchat** [comment]
They sent me here saying it is not planned to be done in bokeh itself (and
apparently could not really be done backend independently if I understood
correctly)
