### ISSUE TITLE
Main wikipage on integration is out of date

### ISSUE THREAD

**Issue by russkel** [bokeh/jupyterlab_bokeh#36]
https://github.com/bokeh/bokeh/wiki/JupyterLab-integration seems out of date.

**Comment by canavandl** [comment]
thanks for pointing that out @russkel 

I removed the JupyterLab-integration page and confirmed that the ``jupyterlab_bokeh`` extension is documented at https://bokeh.pydata.org/en/latest/docs/user_guide/notebook.html. I'm going to close this as resolved - please open a new issue if there's still a problem.
