### ISSUE TITLE
The installation hangs at resolving jupyterlab_bokeh package

### ISSUE THREAD

**Issue by ech2** [bokeh/jupyterlab_bokeh#40]
Hello!

When I try to install the extension, the installation doesn’t progress any further than this:

```
...
[1/4] Resolving packages...
⠂ jupyterlab_bokeh@file:../extensions/jupyterlab_bokeh-0.5.0-b8336c4
```

I tried the following commands (with sudo):

```
jupyter labextension install jupyterlab_bokeh
```

```
npm install
jupyter labextension link .
```

```
npm install
jupyter labextension install .
```

I updated the `jupyterlab` package from PyPI before installation. Both my machines run Manjaro Linux.

Any help would be appreciated.

![2018-05-08-191053_667x724_scrot](https://user-images.githubusercontent.com/1007225/39769035-ab78d058-52f3-11e8-9784-b98239d09c4c.png)

**Comment by ManifoldFR** [comment]
This problem started happening on my machine recently as well. I'm running Windows 10.

**Comment by akiraakaishi** [comment]
I got the same problem with nodejs v10.2.0.
After downgrading nodejs to v9.11.1, I've solved the problem.

**Comment by phlsmk** [comment]
Same problem here with node 10.2.0. downgrading per @akiraakaishi also worked for me

**Comment by shenker** [comment]
Downgrading nodejs from v10.5.0 to v9.11.2 also fixed this problem for me (on linux-64).

**Comment by canavandl** [comment]
This issue is an upstream problem with JupyterLab (jupyterlab/jupyterlab#4986), so I'm going to mark as closed.

If jupyterlab begins to support node@10 and there's a problem with this extension, please reopen this issue.

Thanks for opening the issue!
