### ISSUE TITLE
jupyterlab_bokeh@0.5.0" is not compatible with the current JupyterLab

### ISSUE THREAD

**Issue by dataneupane** [bokeh/jupyterlab_bokeh#47]
Received following error:

jupyterlab_bokeh-0.5.0.tgz

Errored, use --debug for full output:
ValueError: 
"jupyterlab_bokeh@0.5.0" is not compatible with the current JupyterLab
Conflicting Dependencies:
JupyterLab              Extension            Package
>=0.15.4-0 <0.16.0-0    >=0.16.0-0 <0.17.0-0 @jupyterlab/application
>=0.15.5-0 <0.16.0-0    >=0.16.0-0 <0.17.0-0 @jupyterlab/apputils
>=0.15.5-0 <0.16.0-0    >=0.16.0-0 <0.17.0-0 @jupyterlab/notebook
>=1.1.4-0 <2.0.0-0      >=2.0.0-0 <3.0.0-0   @jupyterlab/services

**Comment by canavandl** [comment]
What version of jupyterlab do you have installed? You might have to explicitly install jupyterlab_bokeh@0.4.0 or below.

**Comment by dataneupane** [comment]
I have 0.33.0 JupyterLab 

@canavandl Tried that, did not help

Errored, use --debug for full output:
ValueError: 
"jupyterlab_bokeh@0.4.0" is not compatible with the current JupyterLab
Conflicting Dependencies:
JupyterLab              Extension        Package
>=0.17.2 <0.18.0        >=0.15.0 <0.16.0 @jupyterlab/application
>=0.17.2 <0.18.0        >=0.15.0 <0.16.0 @jupyterlab/notebook
>=3.0.3 <4.0.0          >=1.0.1 <2.0.0   @jupyterlab/services

**Comment by canavandl** [comment]
This issue is resolved by #48 

You should be able to install the the newest jupyterlab_bokeh@0.6.0 package for jupyterlab=0.33.x compat.

Please reopen this issue if your issue isn't resolved.
