### ISSUE TITLE
push_notebook not updating plot

### ISSUE THREAD

**Issue by parente** [bokeh/jupyterlab_bokeh#56]
Installed versions:

* JupyterLab 0.34.12
* ipywidgets 7.4.2
* bokeh 0.13.0 (or falling back to 0.12.6 because of https://github.com/bokeh/bokeh/issues/8122)
* jupyterlab_bokeh 0.6.2

To reproduce:

1. Load the Notebook Handles example (https://bokeh.pydata.org/en/latest/docs/user_guide/notebook.html#notebook-handles)
2. Run the cells up to and including the one that changes the fill color to white and calls `push_notebook`
3. Note the plot does not update.

The JS console appears to contain errors about not being able to register a comm. Best guess: some kind of ipywidgets 7.4 compatibility problem.

**Comment by rcthomas** [comment]
I see the same issue with the interactors demo as well (https://bokeh.pydata.org/en/latest/docs/user_guide/notebook.html#jupyter-interactors)

Same version of everything.  The console says "Exception opening new comm" and then "Object '...' not found in registry"

**Comment by schniewmatz** [comment]
I have the same problem and decided to fall back to an older environment:  
- jupyterlab 0.33.11  
- bokeh 0.12.16  
- ipywidgets 7.4.2  

and installed jupyterlab_bokeh in version 0.6.1
This fallback works for me. You find the environment yml file attached if you want to get back to work fast. You can install it in conda with:  
`conda env create --file environment.yml`

The environment is more or less minimal except for the scipy package.  
I had to zip the file as GitHub does not allow the .yml type to be uploaded
[environment.zip](https://github.com/bokeh/jupyterlab_bokeh/files/2478057/environment.zip)

**Comment by flutefreak7** [comment]
I thought I was getting this issue and somehow discovered that I was using bokeh in JupyterLab without having the extension installed?! I didn't think it was possible to see bokeh javascript content in JupyterLab without the extension - but I was able to do everything except push_notebook just fine.  After installing the extension, push_notebook works for me in JupyterLab now.

I'm wondering if something caused the extension to fall off the list of installed extensions, but still half work in the shadows?  Maybe I updated JupyterLab, but not the extension? Not sure, but a (re)-install of the extension fixed it for me.

**Comment by bryevdv** [comment]
> I'm wondering if something caused the extension to fall off the list of installed extensions, but still half work in the shadows?

I heard the Jupyter devs relented and allowed some limited JS execution without extensions. I have not looked in to things, but that would explain things (and also be the only explanation I can imagine)
