### ISSUE TITLE
Is this required if I have the pyviz jlab extension?

### ISSUE THREAD

**Issue by michaelaye** [bokeh/jupyterlab_bokeh#61]
if not, I think that info could be added to the README?

**Comment by philippjfr** [comment]
Yes, bokeh uses a different MIME renderer extension to display the models. If you don't have or want to install both you can also use [panel](https://github.com/pyviz/panel) to render bokeh models in the notebook (using ``pn.panel``), where you would normally use bokeh's ``show``.

**Comment by michaelaye** [comment]
> Yes, bokeh uses a different MIME renderer extension to display the models.

different as compared to what? I have the pyviz jlab extensions installed and am able to plot via the bokeh extension, but I'm wondering why it works when you say I need this as well. Does it come by default with the hvplot conda package maybe?

**Comment by philippjfr** [comment]
@michaelaye I think I misunderstood you, you only need this bokeh extension when you use bokeh directly. If you're using holoviews/hvplot/panel you don't need this extension as well.

**Comment by michaelaye** [comment]
Oh no, it is me who posed the question confusingly, b/c I only now realize that this is the bokeh org not the ioam org. I think I get confused because you personally seem to be involved in ALL of them, so I can't mentally assign the package to an author cleanly anymore! ;) Thanks for your reply.
