### ISSUE TITLE
AutocompleteWidget shows but dropdown has css or size problem

### ISSUE THREAD

**Issue by TcaManager** [bokeh/jupyterlab_bokeh#64]
Hi,
Awesome work guys!
I'm trying to use an Autocomplete Input Widget in JupyterLab.
It shows up after loading Bokeh and looks perfect.
The HTML behaviour works perfectly, inspecting the code I can see a line for each completion.
But cssly, visually, I have a strange zone where I can't see anything nor click anything.
I guess that problem is very small but can't find a workaround.
Any Idea? Did I miss something?

Here are additional infos, screenshots and html result.

JupyterLab Version 0.35.4
Browser Firefox 52.7.3 and Firefox 67.0 Beta Developer edition
IPython - 7.3.0
Pandas - 0.24.2
Bokeh - 1.0.4
![2019-03-25 17_38_20-JupyterLab - Firefox Developer Edition](https://user-images.githubusercontent.com/30500706/54938173-2afbb000-4f26-11e9-999b-835f33b26f75.png)

```
<div class="bk-root" id="a125a6c8-4ae8-4ab1-9e10-521b544a8a59" data-root-id="1004">
  <div id="AA1D456DFABC4F618379C3426887F247" class="bk-widget bk-widget-form-group bk-layout-fixed bk-bs-open">
    <label for="1004">test</label>
    <input class="bk-widget-form-input bk-autocomplete-input" id="1004" value="ba" placeholder="" type="text">
    <ul class="bk-bs-dropdown-menu">
      <li><a data-text="bar">bar</a></li>
      <li><a data-text="baz">baz</a></li>
    </ul>
  </div>
</div>
```
Thanks!

**Comment by philippjfr** [comment]
Thanks for reporting this, this particular issue should be filed upstream in bokeh, since we have no control over bokeh based models.

**Comment by bryevdv** [comment]
closing for lack of example code, and as mentioned, should go in upstream repo
