### ISSUE TITLE
how to add https to notebook url

### ISSUE THREAD

**Issue by rsinha25** [bokeh/jupyterlab_bokeh#7]
Hi,

I am creating an app in bokeh on jupyterlab and facing a problem with loading the app over https. Below is the code I am trying with the error:

`doc = app.create_document()
show(app, notebook_url='someurl.com:9000')`

Error:
Mixed Content: The page at 'https://someurl.com/user/username/lab?' was loaded over HTTPS, but requested an insecure script 'http://someurl.com:36873/autoload.js?bokeh-autoload-element=066ed1ac-1b69-4246-8878-c9738a09ab8f&bokeh-app-path=/&bokeh-absolute-url=http://someurl.com:36873'. This request has been blocked; the content must be served over HTTPS.

Adding "https" to notebook_url doesn't work and gives an error as below:
`doc = app.create_document()
show(app, notebook_url='https://someurl.com:9000')`

Error:
Invalid host value: https://someurl.com:9000

@canavandl

**Comment by canavandl** [comment]
@rsinha25 I believe this issue would be better addressed in the https://github.com/bokeh/bokeh/issues tracker because it's not a JLab-specific issue (classic notebook would have the same issue). Good luck!
